customhost = "employee.cl8g44imolhb.us-east-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "add1employee12"
customregion = "us-east-1"
